version: '3'
services:
    database:
        image: 'mysql:latest'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: gestion_stock
        ports:
            - '3306'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker_symfony_serveur
        restart: always
        depends_on:
            - database
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
        networks:
            - dev


volumes:
    data1-1:
networks:
    dev:
